#:kivy 1.0.9

#Node for mind map view
<Node@Button>:
    size_hint: None, None
    text_size: 150, None
    halign: 'center'
    size: self.texture_size
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}


<MindMap>:
    canvas:
#        Rectangle:
#            pos: self.center_x - 5, 0
#            size: 10, self.height


#    TextInput:
#        center: self.parent.center


<TextInput>:
    size: 100, 100
    canvas:
        Ellipse:
            pos: self.pos
            size: 200, 200
